### Find instructions here
#### https://github.com/johnwmillr/LyricsGenius/blob/master/README.md

In [ ]:
# #Install lyrics genius module
# !pip install lyricsgenius

In [ ]:
# ## Natural Language Toolkit (NLTK) is a Python package for natural language processing
# ## Install nltk module (for info: https://www.nltk.org/data.html) *takes a while to download*
# !pip install nltk

In [1]:
#Import module and config with token
genius_token = '1tSWz0BRv-X4LPY3d0hOTLGcTIa77N3Sul1XxaJmPpeCHeCe1LrAzHn01cITWAQt'
#for API calls
import requests
import pandas as pd
from pprint import pprint

#for genius.com
import lyricsgenius
# from config import genius_token
genius = lyricsgenius.Genius(genius_token)

# #for nlkt (remove stop words)    ---> all available datasets/models:CORPORA: http://www.nltk.org/nltk_data/
# import nltk
# nltk.download("stopwords")   #can install the “popular” subset of NLTK data, stopwords is included


from nltk.corpus import stopwords 
# from nltk.tokenize import word_tokenize

In [2]:
#RUN WHEN LIST OF SONGS IS AVAILABLE

#Open file with songs from top populated eras
song_with_lyrics_df=pd.read_csv("csv/song_with_lyrics.csv")

# #Drop weird column created for don't know what reason
weird_columns=["Unnamed: 0", "Unnamed: 0.1", "Unnamed: 0.1.1"]
song_list_df=song_with_lyrics_df.drop(weird_columns, axis=1)


song_list_df.head()

,Rank,Song Name,Artist,Duration,Album,Lyrics,Year,bins
0,2,The Scientist,Coldplay,309,A Rush of Blood to the Head,"[Verse 1]\nCome up to meet you, tell you I'm s...",2002,2000s
1,3,Yellow,Coldplay,267,Parachutes,[Verse 1: Chris Martin]\nLook at the stars\nLo...,2000,2000s
2,4,Fix You,Coldplay,294,X&Y,[Verse 1: Chris Martin]\nWhen you try your bes...,2005,2000s
3,5,Chasing Cars,Snow Patrol,0,Eyes Open,[Verse 1]\nWe'll do it all\nEverything\nOn our...,2006,2000s
4,7,I'm Yours,Jason Mraz,242,I'm Yours,"[Verse 1]\nWell, you done done me, and you bet...",2008,2000s

In [3]:
duplicates=song_list_df.duplicated(subset=["Song Name", "Artist"], keep=False)
song_list_df[duplicates]

Empty DataFrame
Columns: [Rank, Song Name, Artist, Duration, Album, Lyrics, Year, bins]
Index: []

In [16]:
#Split lyrics into words, create a new df
import string
punctuation=list(string.punctuation)



# punctuation= [',', '.', ';', ':', '[', ']', '?', '!', '(', ')']

#(for info: https://www.geeksforgeeks.org/removing-stop-words-nltk-python/)
stop_words= set(stopwords.words('english')) 

#possible verse number (as strings)
numbers=[str(n) for n in range(100)]

#possible song structure terms and artist names
song_structure_words=["intro", "verse", "chorus", "bridge", "outro", "hook"]

#list of total words, unique words (arrays) and unique_word_counts (series)
tot_words_list=[]
unique_words_list=[]
unique_words_count_list=[]


for index, row in song_list_df.iterrows():
    
    #Store song lyrics in a variable
    song_lyrics=song_list_df["Lyrics"][index]

    #Before splitting lyrics into words, remove punctation characters
    song_lyrics_clean= song_lyrics

    for x in punctuation:
        if not x == "'":
            song_lyrics_clean=song_lyrics_clean.replace(x,"")
            song_lyrics_clean=song_lyrics_clean.replace(x,"")

    #Split string into list of words
    words_list= song_lyrics_clean.split() 

    #Make df of lowercase words (stop words are all lowercase)
    words_list_lower=[words_list[x].lower() for x in range(len(words_list))]

    #Remove stop words such as “the”, “a”, “an”, “in” 
    filtered_1=[k for k in words_list_lower if not k in stop_words]

    #remove possible verse number (as strings)
    filtered_2=[k for k in filtered_1 if not k in numbers] 

    #remove song structure words     
    filtered_lyrics_index=[k for k in filtered_2 if not k in song_structure_words] 
    
    #Create a df for lyrics analysis
    lyrics_index_df=pd.DataFrame()
 
    #Save song_lyrics_clean to a new dataframe
    lyrics_index_df[index]=filtered_lyrics_index
    
    #Number of words
    tot_words=len(lyrics_index_df[index])
    tot_words_list.append(tot_words)
    
    #Unique words
    unique_words=lyrics_index_df[index].unique()
    unique_words_list.append(unique_words)
    
    #Count of Unique words
    unique_words_count=lyrics_index_df[index].value_counts()
    unique_words_count_list.append(unique_words_count)    
    
    
    #Rename column and export to csv as lyrics_index.csv
    column_name= f'{song_list_df["Song Name"][index]}_{song_list_df["Artist"][index]}'
    lyrics_index_df=lyrics_index_df.rename(columns={index: column_name})
    lyrics_index_df.to_csv(f'Lyrics/lyrics_{index}_df.csv')

lyrics_index_df

   You Wanted More_Tonic
0                   love
1                 tragic
2                   love
3                   bold
4                 always
..                   ...
73                 could
74                handle
75                  life
76                 can't
77                  live

[78 rows x 1 columns]

In [5]:
#list of total words for each song
tot_words_list

[102,
 93,
 85,
 84,
 228,
 112,
 167,
 146,
 130,
 76,
 126,
 135,
 410,
 151,
 121,
 231,
 88,
 153,
 50,
 81,
 153,
 111,
 128,
 101,
 62,
 88,
 217,
 248,
 74,
 122,
 170,
 43,
 65,
 73,
 48,
 217,
 156,
 170,
 110,
 93,
 120,
 103,
 93,
 203,
 53,
 88,
 105,
 72,
 53,
 132,
 88,
 158,
 152,
 135,
 147,
 105,
 183,
 366,
 148,
 195,
 87,
 95,
 256,
 100,
 153,
 260,
 183,
 96,
 146,
 137,
 166,
 113,
 84,
 86,
 122,
 237,
 101,
 282,
 113,
 45,
 301,
 268,
 272,
 202,
 142,
 103,
 128,
 73,
 74,
 141,
 61,
 102,
 111,
 99,
 131,
 120,
 75,
 142,
 170,
 152,
 102,
 61,
 131,
 400,
 107,
 57,
 103,
 99,
 111,
 445,
 158,
 130,
 96,
 96,
 60,
 84,
 392,
 107,
 86,
 147,
 127,
 120,
 63,
 140,
 103,
 130,
 170,
 77,
 252,
 83,
 112,
 122,
 173,
 101,
 316,
 43,
 130,
 139,
 184,
 132,
 165,
 163,
 65,
 83,
 130,
 81,
 240,
 209,
 187,
 97,
 124,
 134,
 76,
 256,
 28,
 120,
 119,
 185,
 114,
 144,
 90,
 137,
 106,
 77,
 182,
 60,
 98,
 161,
 93,
 159,
 132,
 105,
 126,
 163,
 102,
 139,
 158,
 189,
 39,
 135,
 334,
 88,
 1,
 193,
 69,
 193,
 89,
 75,
 135,
 109,
 104,
 94,
 108,
 323,
 96,
 158,
 125,
 102,
 70,
 115,
 191,
 163,
 77,
 331,
 152,
 78,
 23,
 81,
 197,
 93,
 76,
 98,
 171,
 109,
 147,
 156,
 70,
 137,
 105,
 18,
 231,
 64,
 98,
 81,
 203,
 94,
 95,
 235,
 90,
 171,
 114,
 76,
 56,
 33,
 161,
 129,
 167,
 135,
 107,
 145,
 118,
 221,
 121,
 271,
 80,
 138,
 45,
 155,
 142,
 179,
 110,
 170,
 114,
 223,
 137,
 147,
 68,
 184,
 106,
 228,
 166,
 165,
 148,
 112,
 121,
 129,
 199,
 80,
 99,
 118,
 130,
 167,
 122,
 123,
 81,
 139,
 102,
 227,
 59,
 105,
 127,
 245,
 87,
 201,
 147,
 140,
 134,
 135,
 96,
 132,
 130,
 113,
 121,
 72,
 148,
 65,
 36,
 213,
 275,
 176,
 114,
 114,
 144,
 38,
 143,
 142,
 346,
 102,
 124,
 150,
 94,
 136,
 99,
 147,
 138,
 72,
 95,
 86,
 144,
 116,
 94,
 91,
 52,
 51,
 54,
 140,
 190,
 107,
 100,
 57,
 125,
 98,
 153,
 117,
 114,
 141,
 141,
 152,
 146,
 72,
 71,
 157,
 83,
 97,
 87,
 72,
 131,
 176,
 157,
 96,
 77,
 143,
 175,
 202,
 125,
 98,
 66,
 78,
 61,
 143,
 101,
 261,
 131,
 112,
 101,
 129,
 103,
 94,
 147,
 188,
 119,
 159,
 128,
 108,
 110,
 67,
 74,
 384,
 157,
 144,
 163,
 194,
 320,
 116,
 154,
 116,
 77,
 61,
 161,
 87,
 201,
 90,
 175,
 81,
 214,
 144,
 233,
 80,
 114,
 74,
 104,
 120,
 131,
 125,
 162,
 58,
 189,
 143,
 101,
 164,
 111,
 102,
 125,
 138,
 76,
 41,
 90,
 75,
 172,
 85,
 45,
 103,
 47,
 135,
 131,
 57,
 176,
 126,
 140,
 273,
 157,
 172,
 176,
 128,
 116,
 228,
 124,
 191,
 140,
 173,
 119,
 117,
 76,
 201,
 186,
 77,
 113,
 168,
 157,
 145,
 169,
 81,
 152,
 211,
 98,
 133,
 75,
 167,
 43,
 103,
 72,
 82,
 65,
 99,
 47,
 219,
 110,
 173,
 104,
 172,
 60,
 64,
 102,
 250,
 73,
 271,
 187,
 102,
 106,
 85,
 89,
 67,
 106,
 108,
 111,
 82,
 79,
 175,
 111,
 188,
 74,
 73,
 95,
 303,
 105,
 60,
 116,
 83,
 145,
 48,
 89,
 85,
 144,
 109,
 72,
 143,
 78,
 335,
 344,
 132,
 43,
 159,
 94,
 194,
 95,
 122,
 207,
 197,
 262,
 177,
 166,
 116,
 45,
 85,
 95,
 258,
 316,
 123,
 75,
 92,
 98,
 129,
 95,
 164,
 37,
 114,
 116,
 141,
 64,
 101,
 104,
 186,
 96,
 129,
 212,
 90,
 230,
 136,
 142,
 247,
 369,
 1141,
 158,
 149,
 94,
 73,
 109,
 198,
 105,
 77,
 105,
 107,
 69,
 116,
 91,
 131,
 101,
 95,
 120,
 158,
 177,
 67,
 92,
 145,
 152,
 103,
 153,
 106,
 99,
 40,
 78,
 95,
 297,
 41,
 206,
 110,
 87,
 199,
 95,
 95,
 123,
 352,
 162,
 154,
 121,
 84,
 131,
 114,
 256,
 66,
 305,
 72,
 135,
 79,
 94,
 68,
 110,
 107,
 155,
 120,
 131,
 320,
 117,
 371,
 161,
 123,
 126,
 198,
 47,
 154,
 86,
 133,
 327,
 102,
 94,
 210,
 114,
 130,
 153,
 98,
 104,
 101,
 126,
 200,
 52,
 136,
 184,
 175,
 124,
 181,
 79,
 120,
 164,
 50,
 93,
 86,
 56,
 151,
 282,
 112,
 86,
 83,
 138,
 124,
 100,
 94,
 128,
 198,
 126,
 96,
 286,
 187,
 94,
 118,
 417,
 125,
 109,
 70,
 49,
 215,
 92,
 61,
 75,
 46,
 117,
 166,
 204,
 54,
 238,
 192,
 148,
 190,
 62,
 336,
 106,
 135,
 157,
 101,
 99,
 156,
 83,
 179,
 68,
 98,
 178,
 65,
 135,
 151,
 122,
 101,
 168,
 58,
 146,
 79,
 93,
 69,
 91,
 165,
 187,
 82,
 289,
 140,
 102,
 244,
 131,
 154,
 101,
 57,
 86,
 143,
 162,
 131,
 110,
 273,
 144,
 120,
 108,
 148,
 116,
 120,
 195,
 152,
 122,
 234,
 107,
 204,
 85,
 126,
 62,
 182,
 171,
 192,
 157,
 67,
 177,
 147,
 71,
 136,
 91,
 102,
 37,
 112,
 93,
 4027,
 140,
 134,
 180,
 54,
 213,
 89,
 139,
 41,
 99,
 102,
 62,
 139,
 249,
 177,
 329,
 103,
 149,
 84,
 153,
 103,
 178,
 123,
 179,
 246,
 95,
 41,
 172,
 99,
 154,
 183,
 156,
 120,
 255,
 100,
 68,
 114,
 106,
 160,
 136,
 143,
 36,
 84,
 229,
 238,
 210,
 99,
 221,
 210,
 154,
 115,
 62,
 56,
 135,
 209,
 58,
 247,
 89,
 82,
 94,
 210,
 61,
 54,
 156,
 99,
 98,
 192,
 132,
 155,
 133,
 120,
 69,
 44,
 264,
 242,
 104,
 102,
 87,
 132,
 154,
 136,
 218,
 47,
 143,
 256,
 178,
 108,
 146,
 93,
 207,
 61,
 95,
 226,
 183,
 48,
 187,
 75,
 164,
 177,
 109,
 116,
 69,
 96,
 155,
 187,
 213,
 110,
 114,
 138,
 129,
 285,
 160,
 205,
 98,
 291,
 202,
 196,
 72,
 155,
 84,
 374,
 60,
 187,
 92,
 223,
 261,
 249,
 139,
 249,
 204,
 334,
 126,
 76,
 278,
 115,
 1,
 114,
 127,
 80,
 143,
 79,
 101,
 106,
 37,
 207,
 67,
 80,
 113,
 46,
 142,
 132,
 133,
 152,
 171,
 71,
 230,
 129,
 76,
 115,
 272,
 78,
 178,
 285,
 99,
 133,
 107,
 78,
 179,
 56,
 92,
 188,
 125,
 255,
 81,
 191,
 113,
 84,
 267,
 179,
 176,
 101,
 146,
 393,
 102,
 133,
 76,
 96,
 79,
 84,
 73,
 153,
 167,
 122,
 166,
 87,
 79,
 95,
 105,
 349,
 83,
 117,
 54,
 291,
 98,
 73,
 113,
 48,
 135,
 76,
 133,
 182,
 113,
 239,
 59,
 121,
 76,
 121,
 207,
 43,
 98,
 83,
 158,
 83,
 78,
 24,
 138,
 72,
 116,
 130,
 121,
 148,
 126,
 92,
 101,
 130,
 129,
 131,
 662,
 151,
 47,
 117,
 129,
 160,
 60,
 19,
 113,
 189,
 ...]

In [9]:
#list of unique words for each song
unique_words_list
song_list_df['Clean Lyrics'] = unique_words_list

unique_words_df = song_list_df.drop("Lyrics", axis=1)

unique_words_df.head()

,Rank,Song Name,Artist,Duration,Album,Year,bins,Clean Lyrics
0,2,The Scientist,Coldplay,309,A Rush of Blood to the Head,2002,2000s,"[come, meet, tell, i'm, sorry, know, lovely, f..."
1,3,Yellow,Coldplay,267,Parachutes,2000,2000s,"[look, stars, shine, everything, yeah, yellow,..."
2,4,Fix You,Coldplay,294,X&Y,2005,2000s,"[try, best, succeed, get, want, need, feel, ti..."
3,5,Chasing Cars,Snow Patrol,0,Eyes Open,2006,2000s,"[we'll, everything, need, anything, anyone, la..."
4,7,I'm Yours,Jason Mraz,242,I'm Yours,2008,2000s,"[well, done, bet, felt, tried, chill, hot, mel..."

In [13]:
# sort dataframe with lyrics into songs from 2000s
df_00 = unique_words_df.loc[unique_words_df["bins"] == "2000s"]

# export csv of lyrics from the 2000s
df_00_lyrics = df_00['Clean Lyrics']
df_00_lyrics.to_csv("../2000s_lyrics")

C:\Users\17736\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """

In [15]:
# sort dataframe with lyrics into songs from 60s
df_60 = unique_words_df.loc[unique_words_df["bins"] == "60s"]

# export csv of lyrics from the 60s
df_60_lyrics = df_00['Clean Lyrics']
df_60_lyrics.to_csv("../60s_lyrics")

df_60

C:\Users\17736\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

,Rank,Song Name,Artist,Duration,Album,Year,bins,Clean Lyrics
355,42,All You Need Is Love,The Beatles,228,Magical Mystery Tour,1967,60s,"[love, there's, nothing, can't, done, sing, su..."
358,47,Something,The Beatles,159,Abbey Road,1969,60s,"[1something, way, movesattracts, like, loverso..."
366,78,Love Me Do,The Beatles,142,Please Please Me,1962,60s,"[paul, mccartney, &, john, lennon, love, know,..."
367,79,Wouldn't It Be Nice,The Beach Boys,145,Stack-O-Tracks,1966,60s,"[nice, older, wait, long, live, together, kind..."
368,80,I Want to Hold Your Hand,The Beatles,146,1,1963,60s,"[paul, mccartney, &, john, lennon, oh, yeah, i..."
...,...,...,...,...,...,...,...,...
1029,794,Here Comes My Baby,Cat Stevens,176,Matthew & Son,1967,60s,"[midnight, moonlight, i'll, walkin', long, lon..."
1038,823,The Look Of Love,Dusty Springfield,211,The Very Best Of Dusty Springfield,1967,60s,"[look, love, eyes, heart, can't, disguise, say..."
1044,838,Somethin' Stupid,Frank Sinatra,160,The World We Knew,1967,60s,"[vocals, frank, sinatra, &, nancy, know, stand..."
1056,858,"For Emily, Whenever I May Find Her",Simon & Garfunkel,0,NaN,1966,60s,"[dream, pressed, organdy, clothed, crinoline, ..."
1088,951,A House Is Not a Motel,Love,246,Forever Changes,1967,60s,"[house, i've, got, shackles, come, look, want,..."

In [ ]:
#list of unique words counts for each song
unique_words_count_list